name: Build macos-clang

on:
  push:
    branches: [master]
  pull_request:
  workflow_dispatch:

jobs:
  build-opt-off:
    name: "${{matrix.link}}-${{matrix.build-type}}-opt-off"
    runs-on: macos-latest
    env:
      shared: ${{matrix.link == 'SHARED' && 'ON' || 'OFF'}}
    strategy:
      fail-fast: false
      matrix:
        link: ["STATIC", "SHARED"]
        # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
        build-type: ["Debug", "Release"]
        # Support (none, openssl, botan-3, auto)
        tls-provider: ["none"]

    steps:
      - name: Install dependencies
        shell: bash
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: |
          brew install googletest

      - name: Checkout Trantor source code
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Configure Cmake
        run: |
          cmake -B build -S . \
          -DCMAKE_BUILD_TYPE=${{matrix.build-type}} \
          -DBUILD_SHARED_LIBS=$shared \
          -DFETCH_BUILD_MISSING_DEPS=OFF \
          -DTRANTOR_USE_SPDLOG=OFF \
          -DTRANTOR_USE_C-ARES=OFF \
          -DTRANTOR_TLS_PROVIDER=${{matrix.tls-provider}} \
          -DBUILD_TESTING=ON

      - name: Build
        working-directory: ./build
        run: |
          make -j3

      - name: Test
        working-directory: ./build
        run: |
          make test
          
  build-opt-on:
    name: "${{matrix.link}}-${{matrix.build-type}}-TLS:${{matrix.tls-provider}}"
    runs-on: macos-latest
    env:
      shared: ${{matrix.link == 'SHARED' && 'ON' || 'OFF'}}
    strategy:
      fail-fast: false
      matrix:
        link: ["STATIC", "SHARED"]
        # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
        build-type: ["Debug", "Release"]
        # Botan needs std::ranges but clang on macOS doesn't support it yet
        # Support (none, openssl, botan-3, auto)
        tls-provider: ["openssl", "botan-3"]

    steps:
      - name: Install dependencies
        shell: bash
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: |
          brew install googletest spdlog botan

      - name: Checkout Trantor source code
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Configure Cmake
        run: |
          cmake -B build -S . \
          -DCMAKE_BUILD_TYPE=${{matrix.build-type}} \
          -DBUILD_SHARED_LIBS=$shared \
          -DFETCH_BUILD_MISSING_DEPS=OFF \
          -DTRANTOR_USE_SPDLOG=ON \
          -DTRANTOR_USE_C-ARES=ON \
          -DTRANTOR_TLS_PROVIDER=${{matrix.tls-provider}} \
          -DBUILD_TESTING=ON

      - name: Build
        working-directory: ./build
        run: |
          make -j3

      - name: Test
        working-directory: ./build
        run: |
          make test
