name: Build rockylinux-gcc

on:
  push:
    branches: [master]
  pull_request:
  workflow_dispatch:

jobs:
  build-opt-off:
    name: "${{matrix.link}}-${{matrix.build-type}}-opt-off"
    runs-on: ubuntu-latest
    env:
      shared: ${{matrix.link == 'SHARED' && 'ON' || 'OFF'}}
    container:
      image: rockylinux:9.3
      options: --user root
    strategy:
      fail-fast: false
      matrix:
        link: ["STATIC", "SHARED"]
        # Customize the CMake build type here (Release, Debug, RelWithDebInfo, MinSizeRel, etc.)
        build-type: ["Debug", "Release"]
        # Support (none, openssl, botan-3, auto)
        tls-provider: ["none"]

    steps:
      - name: Install build dependencies
        run: |
          dnf install epel-release -y
          dnf install git cmake gcc gcc-c++ gtest-devel -y

      - name: Checkout Trantor source code
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Configure Cmake
        run: |
          cmake -B build -S . \
          -DCMAKE_BUILD_TYPE=${{matrix.build-type}} \
          -DBUILD_SHARED_LIBS=$shared \
          -DFETCH_BUILD_MISSING_DEPS=OFF \
          -DTRANTOR_USE_SPDLOG=OFF \
          -DTRANTOR_USE_C-ARES=OFF \
          -DTRANTOR_TLS_PROVIDER=${{matrix.tls-provider}} \
          -DBUILD_TESTING=ON

      - name: Build
        working-directory: ./build
        run: |
          make -j4

      - name: Test
        working-directory: ./build
        run: |
          make test

  build-opt-on:
    name: "${{matrix.link}}-${{matrix.build-type}}-TLS:${{matrix.tls-provider}}"
    runs-on: ubuntu-latest
    env:
      shared: ${{matrix.link == 'SHARED' && 'ON' || 'OFF'}}
    container:
      image: rockylinux:9.3
      options: --user root
    strategy:
      fail-fast: false
      matrix:
        link: ["STATIC", "SHARED"]
        # Customize the CMake build type here (Release, Debug, RelWithDebInfo, MinSizeRel, etc.)
        build-type: ["Debug", "Release"]
        # Support (none, openssl, botan-3, auto), rockylinux dnf provide botan2
        tls-provider: ["openssl", "botan-3"]

    steps:
      - name: Install build dependencies
        run: |
          dnf install epel-release -y
          dnf install git cmake gcc gcc-c++ -y
          dnf install gtest-devel spdlog-devel c-ares-devel openssl-devel -y

      - uses: actions/cache@v4
        id: rockylinux-cache
        with:
          path: |
            /usr/local/Botan
          key: rockylinux-${{matrix.build-type}}-${{matrix.tls-provider}}

      - name: Checkout Trantor source code
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Configure Cmake
        run: |
          cmake -B build -S . \
          -DCMAKE_BUILD_TYPE=${{matrix.build-type}} \
          -DBUILD_SHARED_LIBS=$shared \
          -DFETCH_BUILD_MISSING_DEPS=OFF \
          -DTRANTOR_USE_SPDLOG=ON \
          -DTRANTOR_USE_C-ARES=ON \
          -DTRANTOR_TLS_PROVIDER=${{matrix.tls-provider}} \
          -DBUILD_TESTING=ON

      - name: Build
        working-directory: ./build
        run: |
          make -j4

      - name: Test
        working-directory: ./build
        run: |
          make test
